Adding changelogs for 0.3.0
scrtlabs/enigma-core pull request #238
Opened 2019-10-18 09:37 UTC by moriaab

@reuvenpo 
I don't have a strong opinion on question: is this the best form to separate the changelog files for `enclave` and `app`? Some of the changes are relevant for the both.
In addition, please review:
* The format of the changelogs
* English
* Belonging of the items to the _"breaking changes"_
Thank you!

2019-10-22 08:14 UTC, reuvenpo requested changes
I think that the format of the changelog is good :)
The points which i mentioned don't belong in "breaking changes" can go in a section before that calles "changes" or "improvements". "improvements is opinionated though.
I think it's ok to combine these files into two files, one at enigma-core and one at enigma-proncipal. the app and enclave parts are always used together (as far as i know) so there isn't much point in talking about them separately.

2019-10-22 08:14 UTC, reuvenpo commented on enigma-core/app/CHANGELOG.md
> +* Adding retries for getting the attestation report from the proxy server. The number of retries may be obtained as an input, otherwise the default number is used.
I think that this isn't a breaking change..?
Is there a reason to think otherwise?

2019-10-22 08:14 UTC, reuvenpo commented on enigma-core/enclave/CHANGELOG.md
> +* Adding ability to revert state
This is only a breaking change if it affects the protocol

2019-10-22 08:14 UTC, reuvenpo commented on enigma-core/enclave/CHANGELOG.md
> +* The length field in serialization of multiple values for hashing is now always a `u64` independent of the platform.
"... independent of the platform running the system (32 vs 64 bit)"

2019-10-22 08:14 UTC, reuvenpo commented on enigma-core/enclave/CHANGELOG.md
> +* Building the state when a computation is executed in a scenario in which the deltas were updated after the epoch has changed.
I'm not quite sure what you mean here. Did you mean:

When a computation is executed after the deltas are updated following an epoch change, *the (contract?) state is rebuilt*

2019-10-22 08:14 UTC, reuvenpo commented on enigma-core/enclave/CHANGELOG.md
> +* Moving storing updated state and delta to the very end of a computation, which prevents possible inconsistency.
storing of updated state and delta is moved to the very end of a computation ...

2019-10-22 08:14 UTC, reuvenpo commented on enigma-principal/app/CHANGELOG.md
> +* Added the ability to add the configuration through environment variables
This is technically a breaking change, but it can be argued that it  isn't. We can keep it here though.

2019-10-25 16:30 UTC, moriaab commented on enigma-core/app/CHANGELOG.md
> +* Adding retries for getting the attestation report from the proxy server. The number of retries may be obtained as an input, otherwise the default number is used.
In my opinion the reason is that there is a new input now, which means API change.

2019-10-27 07:00 UTC, moriaab commented on enigma-core/enclave/CHANGELOG.md
> +* Adding ability to revert state
Yes, it affects the protocol: after the computation is done, the worker updates its state, but if the commit receipt fails, then the p2p part instructs the core to revert the state.

2019-10-27 12:49 UTC, moriaab commented on enigma-core/app/CHANGELOG.md
> +* Adding retries for getting the attestation report from the proxy server. The number of retries may be obtained as an input, otherwise the default number is used.
After discussion with @AvishaiW, we decided that it is not a braking change because there is a default value for the new input. Thanks!

2019-10-27 12:53 UTC, moriaab commented on enigma-principal/app/CHANGELOG.md
> +* Added the ability to add the configuration through environment variables
After your explanation, I prefer to treat it as a breaking change.

2019-10-27 13:00 UTC, moriaab commented on enigma-core/enclave/CHANGELOG.md
> +* Building the state when a computation is executed in a scenario in which the deltas were updated after the epoch has changed.
New formulation: rebuild the state when it was updated by others after the ptt

2019-11-03 13:12 UTC, moriaab commented on enigma-core/enclave/CHANGELOG.md
> +* The length field in serialization of multiple values for hashing is now always a `u64` independent of the platform.
Done

2019-11-03 13:17 UTC, moriaab commented on enigma-core/enclave/CHANGELOG.md
> +* Moving storing updated state and delta to the very end of a computation, which prevents possible inconsistency.
Done

2019-11-03 15:17 UTC, reuvenpo approved these changes

2019-11-03 15:17 UTC, merged