FIX: fixing corner case in factorization secret contract
scrtlabs/enigma-core pull request #269
Opened 2019-12-23 17:24 UTC by moriaab

This PR fixes bug in factorization secret contract: when a number has prime factor greater than its sqrt, it was not counted.

2019-12-24 10:07 UTC, AvishaiW requested changes

2019-12-24 10:07 UTC, AvishaiW commented on examples/eng_wasm_contracts/factorization/src/lib.rs
>                  number = number / i;
I noticed that on square root odd numbers that are prime numbers as well (say 7 for 49, 11 for 121 etc.) will not return the correct answer since the range doesn't cover it. I think you need to add one to the higher bound of the range.

2019-12-24 10:07 UTC, AvishaiW commented on enigma-core/app/src/wasm_u/wasm.rs
> +        let mut encoded_output = symmetric::decrypt(&result.output, &shared_key).unwrap();
it seems that the variables are used for different purposes- IMO that should have different naming for each section, otherwise, it can cause confusion in the future.

2019-12-24 10:07 UTC, AvishaiW commented on examples/eng_wasm_contracts/factorization/src/lib.rs
>                  number = number / i;
another edge case: 0 can't be [right-shifted](https://github.com/enigmampc/enigma-core/pull/269/files#diff-d3895e8dde647512c064d1e384c0e0f1L14) and therefore, returns an error.

2019-12-25 09:03 UTC, moriaab commented on examples/eng_wasm_contracts/factorization/src/lib.rs
>                  number = number / i;
Excellent catch! Thank you!

2019-12-25 13:27 UTC, moriaab commented on enigma-core/app/src/wasm_u/wasm.rs
> +        let mut encoded_output = symmetric::decrypt(&result.output, &shared_key).unwrap();
Ok. Will fix this.

2019-12-29 10:33 UTC, AvishaiW approved these changes
Excellent!

2019-12-29 10:33 UTC, merged