Principal with Key Management
scrtlabs/enigma-core pull request #89
Opened 2019-03-14 06:31 UTC by fredfortier

Notes:
- Deploying the Enigma contract does not work. You'll notice that related sections of the code are commented out. I did not completely remove them because we may want to re-enable them or adapt to your integration test framework. There are two reasons why I chose to disable this: 
  1. Rust Web3 does not support deploying contracts with linked libraries: https://github.com/tomusdrw/rust-web3/issues/186. We could submit a PR to enable it but I determined that it was not a priority.
  2. New business logic like the worker selection algorithm requires extensive setup (registering multiple workers, crossing epoch, etc).

  Here is what I did to compensate:
  1. Added lower level unit tests with mock data that does not interface with the live contract.
  2. Made the CLI commands more granular (which useful beyond testing) and added a mode to `Enigma.specs.js` that invokes the live Principal node. This way, we can substitute the mock for live Principal node and without changing the tests. This was the most convenient way for me to test and also a good bridge to the full integration test script.
- Added a `confirmations` parameter to the `enigma_contract` module in addition to supporting the new methods in the contract.
- I'm using a specific terminology for some of the for the `epoch` and `keys` modules. I'm also using the `_u` and `_t` but there was still overlap: 1) Provider: Provide external data; 2) Keeper: Store and verify data in the enclave. I'm happy to refactor this if you suggest a different convention.
- The `keys_keeper_types` module is copied across: `app/src/esgx/keys_keeper_u.rs` and `enclave/src/keys_keeper_t/keeper_types_t.rs`. I tried to make a reusable module that works both in the enclave and out ran into issues and aborted for now.
- I created `enigma-tools-t/src/document_storage_t.rs` which is based upon `storage_t.rs` but supports variable byte array size. It also has improved error handling. I believe that it can replace `storage_t.rs`.

TODOs:
- Seal the epoch data. I have a plan for this to did not have time to finish. Instead of sealing the entire epoch data, I want to seal the nonce + a hash. The `epoch_provider` will fetch the epoch data and call `set_worker_params` and pass the nonce. Instead of incrementing the nonce, the `epoch_keeper` will verify the data against the hash and store in memory.
- I could not get the Makefile to copy `enigma-types.h` in the enclave folder. I included a temporary workaround on line 111 of `enigma-principal/Makefile`. I would appreciate if you could take a look. This causes the build to fail on the CI server.
- Worker selection is disabled for the time being (it always return the keys). I'm working on testing more thoroughly and will push an update shortly.
- I cherry picked commit 346a8e40827ee4f9af0f56186d72ac916f26cf6f because I needed a working SPID. Now the `attestation_service::service::test` tests are failing. The root cause is not obvious to me. I will wait until the related PR is finalized to troubleshoot.
- Logging is not implemented in the enclave.

2019-03-14 10:37 UTC, elichai requested changes
Ok, this is my first pass of the code.
It's really really hard to review such a big PR. 
next time please try to split into little PRs,
this will help you with the need to always merge from develop and will help me in reviewing.

2019-03-14 10:37 UTC, elichai commented on eng-wasm/dispatch/src/lib.rs
> +#![recursion_limit="128"]
What's the deal with the `eng-wasm/dispatch`?  I think this is something from a merge got wrong.

2019-03-14 10:37 UTC, elichai commented on enigma-core/app/enigma-core-app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please add the `iml`  files to the `.gitignore`

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/keys_provider_http.rs
> +        let reader = PrincipalMessageReader::new(request.data.clone().into())?;
the `Into` here contains an unwrap. this means that if you receive a non hex string in the JSON-RPC the principal node will crash.
I think the principal node should be a lot more robust, at least in the interface side.

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/epoch_u/epoch_provider.rs
> +    pub eid: Arc<AtomicU64>,
I think the `eid` can be regular `u64` and doesn't need to be `AtomicU64` because there's no need to it to be atomic because it should never change.

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/keys_provider_http.rs
> +            .cors(DomainsValidation::AllowOnly(vec![AccessControlAllowOrigin::Null]))
What is the need for CORS headers?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +    fn get_account_address(&self) -> Address { self.contract.account.clone() }
`Address` Implements `Copy` so no need to clone it.

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let block_number = self.get_web3().eth().block_number().wait().unwrap();
Why do you unwrap if you return a result?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let receipt = self.contract.register(signing_address, report, signature, gas_limit, self.config.confirmations as usize)?;
```suggestion
        let receipt = self.contract.register(signing_address, registration_params.report, registration_params.signature, gas_limit, self.config.confirmations as usize)?;
```
You can pass the report and signature directly without cloning them in memory

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let eid: Arc<AtomicU64> = Arc::new(AtomicU64::new(self.eid));
Again, the eid can stay u64 (or more clearly `sgx_enclave_id_t`)

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/boot_network/principal_manager.rs
>      fn test_full_principal_logic() {
Why is this test commented out?
I think it's a pretty important test, unless there's a different test that checks if random emission with simulated blocks

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/cli/app.rs
> +    let _config = deploy_scripts::load_config(opt.deploy_config.as_str())?;
If you don't use this config why not remove it?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/cli/app.rs
> +        path.push("principal-sign-addr.txt");
Why do you save the signing address to a file?

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +#[cfg(not(target_env = "sgx"))]
You can remove this.
It's something old that we don't use.

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +        let sealed_data = match from_sealed_log::<Self>(sealed_log, sealed_log_size as u32) {
I think this should get a deeper look to see if we can use the "safer" ` unseal_data()`

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +        to_sealed_log(&sealed_data, sealed_log, sealed_log_size as u32);
Is that really needed? can we just use the Self this returns?
I'll prefer if we didn't use the unsafe functions here.

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +            data: [0; 32],
```suggestion
            data: [b'i'; 32],
```

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +            data: [0; 32],
Then you can remove the for loop

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +pub const SEAL_LOG_SIZE: usize = 2048;
Why is the whole 2048?
What if you sealed a `[u8; 8096]`?

2019-03-14 10:37 UTC, elichai commented on enigma-tools-t/Cargo.toml
> +cargo-features = ["rename-dependency"]
Why do you need this? I don't see any dependency that you're renaming

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/lib.rs
> +    let response = match ecall_get_enc_state_keys_internal(msg_bytes, addrs_bytes, sig.clone(), sig_out) {
why clone the signature?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/esgx/keys_keeper_u.rs
> +    let mut enc_response = vec![0u8; MAX_ENC_RESPONSE_LEN];
What if it's higher than 100_000?
you should use: https://github.com/enigmampc/enigma-core-internal/blob/develop/enigma-core/enclave/src/ocalls_t.rs#L26
And then you unbox the memory, see this for reference: 
https://github.com/enigmampc/enigma-core-internal/blob/develop/enigma-core/app/src/km_u.rs#L65

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +        if key.is_none() {
you can put in `Some(key) => results.push(key.clone())` and in None => everything you did in `if key.is_none()`

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +        let mut rand_seed: [u8; 1072] = [0; 1072];
Why do you generate a whole MegaByte of random just to take the first 32 bytes?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let sc_addrs: Option<Vec<ContractAddress>> = match msg.data.clone() {
Why an option of vec and not just a vec and then you could return an empty one?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +fn build_get_state_keys_response(_sc_addrs: Option<Vec<ContractAddress>>) -> Result<Vec<(ContractAddress, StateKey)>, EnclaveError> {
you can receive here a vec and just check if it's empty. no need for the Option.
this will remove an `unwrap` and make the code look nicer.

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let mut rand_num: [u8; 1072] = [0; 1072];
Again, a whole MB for just 44 bytes?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/keeper_types_t.rs
> +            block_number: U256::from_bigint(rlp.val_at(0)?),
What's up with these bigints?
I can't see them in the docs of etccommon-rlp, where do they come from? do we really need to have bigint as a dependency? https://docs.rs/etcommon-rlp/0.2.4/rlp/trait.Decodable.html

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    // TODO: Check if needs to check the random is within the curve.
curve?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    let sig = SIGNING_KEY.sign(hash.as_ref())?;
You know that the sign message already hash the data. right?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +        version: 0x1234, //TODO: what's this?
Right. what is this? :)

2019-03-14 10:37 UTC, elichai commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    guard.keys().max().unwrap().clone()
Can the HashMap be empty?
If so maybe do `unwrap_or_deafult()` to return `0` in the case it's empty?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/logging.rs
> +use std::{fs::{self, File}, path::Path};
maybe this file can be moved to `enigma-tools-u`

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/keys_u/km_reader.rs
> +pub struct PrincipalMessage {
Why are you deserializing this outside of the enclave?
Why not pass it directly to the enclave and deserialize it && verify the signature there?

2019-03-14 10:37 UTC, elichai commented on enigma-principal/app/src/epoch_u/epoch_types.rs
> +        s.append_list(&self.workers.iter().map(|a| a.bigint()).collect::<Vec<bigint::H160>>());
Again, I can't seem to find where the bigint comes from.
https://docs.rs/etcommon-rlp/0.2.4/rlp/trait.Encodable.html

2019-03-14 11:09 UTC, elichai commented on enigma-tools-u/src/web3_utils/w3utils.rs
> +    let w3 = web3::Web3::new(web3::transports::Batch::new(http));
```suggestion
    web3::Web3::new(web3::transports::Batch::new(http))
```
You can return this directly

2019-03-14 11:30 UTC, elichai commented on enigma-principal/app/src/esgx/keys_keeper_u.rs
> +    let enc_response_out: Vec<u8> = enc_response_slice[0..enc_response_len_out].iter().cloned().collect();
```suggestion
    let enc_response_out: Vec<u8> = enc_response_slice[0..enc_response_len_out].to_vec()
```
This should be faster and is more readable

2019-03-14 11:33 UTC, elichai commented on enigma-principal/app/src/epoch_u/epoch_provider.rs
> +        let receipt = self.contract.set_workers_params(block_number, epoch_state.seed.clone(), epoch_state.sig.clone(), gas_limit, confirmations)?;
No need to clone the seed, it's a `Copy` type

2019-03-14 11:36 UTC, elichai commented on enigma-principal/app/src/keys_u/keeper_types_u.rs
> +            for i in 0..self.workers.len() {
why not just `for worker in self.workers` ?

2019-03-14 15:28 UTC, fredfortier commented on eng-wasm/dispatch/src/lib.rs
> +#![recursion_limit="128"]
I hadn't noticed this. I will investigate.

2019-03-14 15:34 UTC, fredfortier commented on enigma-principal/app/src/cli/app.rs
> +        path.push("principal-sign-addr.txt");
This is important for integration testing. The contract deployment script reads the address from here.

2019-03-14 15:38 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +        let sealed_data = match from_sealed_log::<Self>(sealed_log, sealed_log_size as u32) {
Most this file comes from the original `storage_t`. I haven't look at optimizations beyond variable length and error handling. I will do some research on this safer `unseal_data`.

2019-03-14 15:40 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +pub const SEAL_LOG_SIZE: usize = 2048;
That's just the default value that was already. This should be enough for the data that I'm storing but I'll research this to see if can be more dynamic.

2019-03-14 15:42 UTC, elichai commented on enigma-tools-t/src/document_storage_t.rs
> +        let sealed_data = match from_sealed_log::<Self>(sealed_log, sealed_log_size as u32) {
and it works? I'm actually pretty surprised, because the old `storage_t` was written before we really understood a lot and it's pretty hacky, so I'm surprised it works for bigger data

2019-03-14 15:43 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +        let mut rand_seed: [u8; 1072] = [0; 1072];
This is how I've need in done in the existing code. I'll research further to better understand the `rand` function.

2019-03-14 15:45 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    // TODO: Check if needs to check the random is within the curve.
This comes from the original code. I believe that Isan wrote this comment. I don't understand it  either but did not want to lose track of it.

2019-03-14 15:51 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/keeper_types_t.rs
> +            block_number: U256::from_bigint(rlp.val_at(0)?),
It's required to use this particular ectcommon RLP Crate. These crates use `bigint` instead of `ethereum-types`. I suppose that I could use a different encoding method here since RLP is no longer imperative.

2019-03-14 15:54 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    let sig = SIGNING_KEY.sign(hash.as_ref())?;
Ah! Thanks for reminding me. This explain the issue. I'm not sure how I got it mixed-up.

2019-03-14 15:55 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +        version: 0x1234, //TODO: what's this?
I have no idea. This comes from the original `storage_t`. I tried not to break things that I did not understand. Isan might know.

2019-03-14 16:07 UTC, fredfortier commented on enigma-principal/app/src/keys_u/km_reader.rs
> +pub struct PrincipalMessage {
Here is the logic:
1. The list of contract => selected worker is stored on the untrusted side
2. Here, I read the message to verify if the list of addresses is None. If so, I find the contract addresses for this worker in the epoch and pass to the enclave along with the message.
3. If the message does contain a list of addresses, I just pass the message to the enclave.
4. In the enclave, I deserialize the message again and read the addresses either from the message or, in None, from the list passed by the untrusted. I also verify the signature and run the worker selection algorithm to confirm that the addresses are valid.

This approach achieves two things:
 1. Allow messages to pass-through the the enclave so that the untrusted side cannot censor the addresses that it may contain.
2. Keeps the list of secret contracts on the untrusted side. It would be hard to prove this list to the enclave. At most, the untrusted side could censor secret contract addresses selected for the worker. However, the worker could simply follow-up with a message requesting the missing addresses which the untrusted side cannot modify.

2019-03-14 16:07 UTC, fredfortier commented on enigma-principal/app/src/epoch_u/epoch_types.rs
> +        s.append_list(&self.workers.iter().map(|a| a.bigint()).collect::<Vec<bigint::H160>>());
Sam answer as above. It's the types primitive for etccommon modules.

2019-03-14 16:12 UTC, fredfortier commented on enigma-principal/app/src/epoch_u/epoch_provider.rs
> +    pub eid: Arc<AtomicU64>,
I wasn't able to pass a u64 across threads but will try again.

2019-03-14 16:13 UTC, fredfortier commented on enigma-tools-u/src/web3_utils/w3utils.rs
> +    let w3 = web3::Web3::new(web3::transports::Batch::new(http));
You're right. I'm not using the batch transport anymore. I will clean-up.

2019-03-14 16:27 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +        let sealed_data = match from_sealed_log::<Self>(sealed_log, sealed_log_size as u32) {
Yes, it works for variable size of byte arrays. I'm not trying to store large documents at the moment. Do you have an example of a more mature implementation of storage which I can review?

2019-03-14 16:31 UTC, fredfortier commented on enigma-principal/app/src/keys_u/keeper_types_u.rs
> +            for i in 0..self.workers.len() {
Because I need the index in the line below.

2019-03-15 21:19 UTC, fredfortier commented on eng-wasm/dispatch/src/lib.rs
> +#![recursion_limit="128"]
Fixed

2019-03-15 21:44 UTC, fredfortier commented on enigma-core/app/enigma-core-app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed

2019-03-15 22:26 UTC, fredfortier commented on enigma-principal/app/src/boot_network/keys_provider_http.rs
> +        let reader = PrincipalMessageReader::new(request.data.clone().into())?;
Good catch! Fixed in commit a2c322bc89442eaa0f2b175f400fcf53eb424988.

2019-03-15 22:30 UTC, fredfortier commented on enigma-principal/app/src/boot_network/keys_provider_http.rs
> +            .cors(DomainsValidation::AllowOnly(vec![AccessControlAllowOrigin::Null]))
The parameter was removing CORS header verification. I set it for troubleshooting as one point in time but you are correct that it's not needed. Removed in commit 5d2285cdfe8d20f05d7b9c88a11a173efc93ad4f.

2019-03-15 22:37 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +    fn get_account_address(&self) -> Address { self.contract.account.clone() }
Interesting, I did not realize that implementing the `Copy` trait implicitly cloned the variable instead of moving. I thought that it still needed to be specified explicitly. My IDE does not seem to support this but the compiler is happy with it. I'll inspect throughout and create a single commit.

2019-03-15 22:46 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let block_number = self.get_web3().eth().block_number().wait().unwrap();
Yes, I forgot to handle this. Fixed in commit 031fd8c363fa5688e64bd95558f29540aca50e14.

2019-03-15 22:52 UTC, fredfortier commented on enigma-principal/enclave/src/lib.rs
> +    let response = match ecall_get_enc_state_keys_internal(msg_bytes, addrs_bytes, sig.clone(), sig_out) {
Fixed in commit e7adf35481143153d4b637aa8f6ae93499172d2e.

2019-03-15 22:53 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let receipt = self.contract.register(signing_address, report, signature, gas_limit, self.config.confirmations as usize)?;
Fixed in commit: e7adf35481143153d4b637aa8f6ae93499172d2e.

2019-03-15 23:02 UTC, fredfortier commented on enigma-principal/app/src/cli/app.rs
> +    let _config = deploy_scripts::load_config(opt.deploy_config.as_str())?;
Fixed in 68afcef246bbe4978d4ab94501853b45ead7fd67.

2019-03-15 23:11 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +        to_sealed_log(&sealed_data, sealed_log, sealed_log_size as u32);
This is just an adaptation of `storage_t` which I assumed was current. I need to better understand the storage service to answer this. Is there a better example than `storage_t` in our code? If not, I research in the Baidu SDK.

2019-03-15 23:13 UTC, fredfortier commented on enigma-tools-t/Cargo.toml
> +cargo-features = ["rename-dependency"]
Forgot to remove the feature after experimenting with it. Fixed in commit bed425e47186a9933bc4329680ffa9aeb31ad2cb.

2019-03-15 23:16 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +#[cfg(not(target_env = "sgx"))]
Removed in commit b9f50bc39689924bc12c3f0e14ee5792b72c861d.

2019-03-15 23:27 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +        if key.is_none() {
I implemented it like this for a specific reason, putting the `key.is_none()` logic in the match fn gives an immutable (`guard get`) and mutable (`guard.insert`) borrow conflict.

2019-03-15 23:31 UTC, fredfortier commented on enigma-tools-u/src/web3_utils/w3utils.rs
> +    let w3 = web3::Web3::new(web3::transports::Batch::new(http));
Removed `connect_batch` in commit b9f50bc39689924bc12c3f0e14ee5792b72c861d.

2019-03-15 23:34 UTC, fredfortier commented on enigma-principal/app/src/epoch_u/epoch_provider.rs
> +        let receipt = self.contract.set_workers_params(block_number, epoch_state.seed.clone(), epoch_state.sig.clone(), gas_limit, confirmations)?;
Adjusted in commit 762ae1c73e8e00ab8c54fcc6c4e9c5eb788d1d32.

2019-03-15 23:57 UTC, fredfortier commented on enigma-principal/app/src/logging.rs
> +use std::{fs::{self, File}, path::Path};
Refactored in commit f548eafbf818bd9c44486a3f4b0d673971e97afc. There is more code copy/pasted especially in `enigma-principal/app/src/esgx` module. I tried to not to question functioning code and limit impact on shared modules, but it's probably worth refactoring this area.

2019-03-16 00:03 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
>      fn test_full_principal_logic() {
Yes, I explained this in the notes included in the PR. That said, I agree that this test is useful. I just did not prioritize refactoring it since I have another way to test. I will re-enable it shortly.

2019-03-16 00:15 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let mut rand_num: [u8; 1072] = [0; 1072];
Fixed in commit 1df39b26a9e42561bd03defb2c5136408846a391.

2019-03-16 00:17 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +        let mut rand_seed: [u8; 1072] = [0; 1072];
Thanks for catching this. Fixed in commit 1df39b26a9e42561bd03defb2c5136408846a391.

2019-03-16 00:37 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    guard.keys().max().unwrap().clone()
No, it can't, there is a guard clause before its usage. Since this fn was only used once, I refactored it to put the logic directly after the guard clause. I can see how this wasn't very readable. Commit dd39e025a5b34eecd022a5071f6588798cdc49cd.

2019-03-16 00:42 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    // TODO: Check if needs to check the random is within the curve.
Removed the TODO in 3d1f5d0f650db92fb9f3f0ff3125074c497d4cc6.

2019-03-16 00:43 UTC, fredfortier commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +    let sig = SIGNING_KEY.sign(hash.as_ref())?;
Removed the redundant hashing in commit 3d1f5d0f650db92fb9f3f0ff3125074c497d4cc6.

2019-03-16 00:55 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let sc_addrs: Option<Vec<ContractAddress>> = match msg.data.clone() {
You're right, the option is unnecessary and the code looks cleaner without. Commit e6592f92c553e998e5dbb454861702eb027b2d61.

2019-03-16 00:55 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +fn build_get_state_keys_response(_sc_addrs: Option<Vec<ContractAddress>>) -> Result<Vec<(ContractAddress, StateKey)>, EnclaveError> {
Refactored in commit e6592f92c553e998e5dbb454861702eb027b2d61.

2019-03-16 00:59 UTC, fredfortier commented on enigma-tools-t/src/document_storage_t.rs
> +            data: [0; 32],
Obviously :smile: Commit 1bcbdd7da8841587d357af9b77be98dea69b83eb.

2019-03-17 08:41 UTC, elichai commented on enigma-principal/app/src/keys_u/keeper_types_u.rs
> +            for i in 0..self.workers.len() {
Ok, FYI best practice is `enumerate` https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate

2019-03-17 09:16 UTC, elichai commented on enigma-principal/enclave/src/epoch_keeper_t/mod.rs
> +        version: 0x1234, //TODO: what's this?
I think this is a feature that @Isan-Rivkin thought might be useful for the signing keys, I don't think there's a use case here and even in the signing keys we didn't end up using this.

2019-03-17 12:26 UTC, elichai commented on dockerfile/run.sh
> +#!/usr/bin/env bash
I'm not sure if that's the right place for this. e.g. I just had this in my `.bash_aliases`/`.bashrc`:
```
alias enigma-docker='docker run --security-opt seccomp:unconfined --cap-add=SYS_PTRACE --net="host" -v /home/elichai2/CLionProjects/enigma-core:/home/elichai2/enigma-core -v /home/elichai2/.cargo-enigma-docker:/home/elichai2/.cargo -ti --device /dev/isgx enigma_dev:latest'
```
So I don't think that your exact preferences should be in the git

2019-03-17 13:29 UTC, elichai commented on .gitignore
> +**/*.rs.bk
You wrote this twice.

2019-03-17 15:23 UTC, elichai commented on enigma-principal/enclave/src/lib.rs
> +    println!("The priv key for worker 8: {:?}", SIGNING_KEY.get_privkey().to_vec().to_hex());
I'm gessing you meant to remove this.

2019-03-17 16:05 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/keeper_types_t.rs
> +            block_number: U256::from_bigint(rlp.val_at(0)?),
hmm ok, I still haven't looked into where is this used but I also don't like the endianess assumeption here.
what if `ethereum-types::U256` and `etcommon-bigint::U256` don't use the same endianess?

2019-03-19 02:25 UTC, fredfortier commented on enigma-principal/enclave/src/lib.rs
> +    println!("The priv key for worker 8: {:?}", SIGNING_KEY.get_privkey().to_vec().to_hex());
Fixed c8ecac858baab8e1445c524e6103b2c6df3d3f76

2019-03-19 02:53 UTC, fredfortier commented on .gitignore
> +**/*.rs.bk
Fixed 90deb885612469ce15129c979a16cabe78c09549

2019-03-19 03:05 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
> +        let eid: Arc<AtomicU64> = Arc::new(AtomicU64::new(self.eid));
Fixed a62f7c406935853558959cd57ceed2300154e3ce

2019-03-19 03:05 UTC, fredfortier commented on enigma-principal/app/src/epoch_u/epoch_provider.rs
> +    pub eid: Arc<AtomicU64>,
Fixed a62f7c406935853558959cd57ceed2300154e3ce

2019-03-19 12:29 UTC, moriaab commented on enigma-principal/app/src/boot_network/keys_provider_http.rs
> +        slice.copy_from_slice(&bytes[..]);
The length of source must be the same as self in copy_from_slice, the function will panic otherwise. String can be any length. You should check it somehow or do it safer.

2019-03-19 13:58 UTC, moriaab commented on enigma-principal/app/src/main.rs
>  fn main() {
@elichai, @fredfortier
This is a general comment. We have duplicated code in functions `main` in enigma-core/app/src/main.rs and enigma-principal/app/src/main.rs: from the first line to getting eid. I think it is better to extract it to untrusted common utils.

2019-03-19 17:44 UTC, elichai commented on enigma-principal/app/src/esgx/equote.rs
> +    fn ecall_get_signing_address(eid: sgx_enclave_id_t, pubkey: &mut [u8; 20]) -> sgx_status_t;
You changed the signature here but didn't change it in the EDL or in the trusted side.
This means the edgerator just memcpy's another 22 bytes that just exist after this array. I'm suprised you didn't have any segmentation faults.

2019-03-19 17:58 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let response = response_msg.encrypt_with_nonce(&derived_key, Some(iv))?;
`encrypt_with_nonce` shouldn't be called directly, it's for internal use and tests.
I'll make a PR that adds a warning there.

2019-03-19 17:59 UTC, elichai commented on enigma-principal/enclave/src/lib.rs
> +    let addrs_bytes = slice::from_raw_parts(addrs, addrs_len).to_vec();
No need to convert these to vectors, you can pass them as slices directly.

2019-03-19 18:08 UTC, elichai commented on enigma-principal/app/src/esgx/keys_keeper_u.rs
> +            addrs_bytes.as_ptr() as *const u8,
We should always use `as_c_ptr()`(https://github.com/enigmampc/enigma-core-internal/blob/develop/enigma-types/src/traits.rs#L3) otherwise if the slice/vec is empty it will return a ptr 0x0, which isn't a defined behavior in C, so this causes SegFaults.

2019-03-19 18:15 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let key_pair = KeyPair::from_slice(&privkey_slice)?;
Please use `KeyPair::new()` as the generated private key might not be valid for the curve. it should be checked (which `KeyPair::new()` does)

2019-03-19 18:20 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    if !response_msg.is_response() {
Why do you check if it's not a response right after you made it as a response?

2019-03-19 18:27 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let hash = response_bytes.clone().keccak256();
You're hashing before the sign function which already hashes for you.

2019-03-20 03:38 UTC, fredfortier commented on enigma-principal/app/src/boot_network/principal_manager.rs
>      fn test_full_principal_logic() {
Fixed the unit test (minus contract deployment) 31888b32e95a4a7471e809442e465a89c9195c36

2019-03-20 03:45 UTC, fredfortier commented on enigma-principal/app/src/esgx/equote.rs
> +    fn ecall_get_signing_address(eid: sgx_enclave_id_t, pubkey: &mut [u8; 20]) -> sgx_status_t;
The trusted side looks fine but I fixed the mismatching EDL f58c88976c52619e382b724ddb31587d204d5dad

2019-03-20 03:48 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let response = response_msg.encrypt_with_nonce(&derived_key, Some(iv))?;
I don't see any abstraction in the `km_primitive` module.

2019-03-20 03:56 UTC, fredfortier commented on enigma-principal/enclave/src/lib.rs
> +    let addrs_bytes = slice::from_raw_parts(addrs, addrs_len).to_vec();
My compiler wants me to. I'm not sure why it's using a `Vec` implementation. I believe that I'm importing it correctly.
```
error[E0308]: mismatched types
   --> src/lib.rs:103:60
    |
103 |     let response = match ecall_get_enc_state_keys_internal(*msg_bytes, *addrs_bytes, *sig, sig_out) {
    |                                                            ^^^^^^^^^^
    |                                                            |
    |                                                            expected struct `serde::export::Vec`, found slice
    |                                                            help: try using a conversion method: `*msg_bytes.to_vec()`
    |
    = note: expected type `serde::export::Vec<u8>`
               found type `[u8]`
```

2019-03-20 04:05 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let key_pair = KeyPair::from_slice(&privkey_slice)?;
Fixed 951089c26472ff38de1975e13f5c7bb492e6db27

2019-03-20 04:07 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    if !response_msg.is_response() {
I was trying to account for the possibility that the message is not initialized correctly. After looking more closely at what `new_id` does, I agree that it is redundant. Fixed 951089c26472ff38de1975e13f5c7bb492e6db27

2019-03-20 04:07 UTC, fredfortier commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let hash = response_bytes.clone().keccak256();
Fixed 951089c26472ff38de1975e13f5c7bb492e6db27

2019-03-20 08:11 UTC, elichai commented on enigma-principal/enclave/src/keys_keeper_t/mod.rs
> +    let response = response_msg.encrypt_with_nonce(&derived_key, Some(iv))?;
I wrote that trait in a way that you need to implement `encrypt_with_nonce` and you get `encrypt` for free https://github.com/enigmampc/enigma-core-internal/blob/develop/enigma-crypto/src/lib.rs#L37

2019-03-20 08:11 UTC, elichai commented on enigma-principal/enclave/src/lib.rs
> +    let addrs_bytes = slice::from_raw_parts(addrs, addrs_len).to_vec();
Change `ecall_get_enc_state_keys_internal` to accept slices

2019-03-20 08:14 UTC, elichai commented on enigma-principal/app/src/esgx/equote.rs
> +    fn ecall_get_signing_address(eid: sgx_enclave_id_t, pubkey: &mut [u8; 20]) -> sgx_status_t;
That's because you fixed it here :) https://github.com/enigmampc/enigma-core-internal/pull/89/commits/45a294ae75c62b62b91020fd053521727a4f7545

2019-04-03 16:27 UTC, elichai approved these changes

2019-04-03 16:50 UTC, merged